export const CUSTOM_ADDED_TAGS = Object.freeze({
    ADD_TAGS: ['icon'],
    ADD_ATTR: [
        'filled',
        'size-xsmall',
        'size-x-small',
        'size-small',
        'size-medium',
        'size-large',
        'size-xlarge',
        'size-x-large',
        'size-xxlarge',
        'size-xx-large',
        'decor-underline',
        'decor-overline',
        'decor-strike',
        'decor-none',
        'decor-style-solid',
        'decor-style-double',
        'decor-style-dotted',
        'decor-style-dashed',
        'decor-style-wavy',
        'decor-skip-ink',
        'decor-skipink',
        'decor-skip-ink-auto',
        'decor-skipink-auto',
        'decor-skip-ink-all',
        'decor-skipink-all',
        'decor-skip-ink-none',
        'decor-skipink-none',
        'bold',
        'italic',
    ],
});
